# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../Make.inc

TARG=testing
GOFILES=\
	benchmark.go\
	example.go\
	testing.go\
	wrapper.go\

include ../../Make.pkg
