# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../Make.$(GOARCH)

TARG=http
GOFILES=\
	chunked.go\
	client.go\
	dump.go\
	fs.go\
	lex.go\
	persist.go\
	request.go\
	response.go\
	server.go\
	status.go\
	transfer.go\
	url.go\

include ../../Make.pkg
