# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../Make.inc

TARG=sync
GOFILES=\
	cond.go\
	mutex.go\
	once.go \
	rwmutex.go\
	waitgroup.go\

include ../../Make.pkg
