# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=go/ast
GOFILES=\
	ast.go\
	filter.go\
	import.go\
	print.go\
	resolve.go\
	scope.go\
	walk.go\

include ../../../Make.pkg
