# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 1
updates:
 - package-ecosystem: "devcontainers"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
 - package-ecosystem: "dockerfile"
   directory: home/.devcontainer
   schedule:
     interval: weekly
