#!/bin/bash

eval $(go env)

export NACLENV_GOARCH=$GOARCH
export NACLENV_GOOS=$GOOS
export NACLENV_GOROOT=/go
export NACLENV_NACLPWD=$(pwd | sed "s;$GOROOT;/go;")

exec sel_ldr_x86_64 -l /dev/null -S -e "$@"
