// generated by gengoos.go using 'go generate'

package runtime

const theGoos = `dragonfly`

const goos_android = 0
const goos_darwin = 0
const goos_dragonfly = 1
const goos_freebsd = 0
const goos_linux = 0
const goos_nacl = 0
const goos_netbsd = 0
const goos_openbsd = 0
const goos_plan9 = 0
const goos_solaris = 0
const goos_windows = 0
