# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../Make.$(GOARCH)

TARG=html
GOFILES=\
	doc.go\
	entity.go\
	escape.go\
	token.go\

include ../../Make.pkg
