# Copyright 2011 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=compress/bzip2
GOFILES=\
	bit_reader.go\
	bzip2.go\
	huffman.go\
	move_to_front.go\

include ../../../Make.pkg
