# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=go/types
GOFILES=\
	const.go\
	exportdata.go\
	gcimporter.go\
	types.go\
	universe.go\

include ../../../Make.pkg
