// Code generated by 'simdgen -o godefs -goroot $GOROOT -arm64Path $ARM64_ISA_PATH go_arm64.yaml types.yaml categories.yaml'; DO NOT EDIT.

package main

func simdARM64Ops(v11, v21, vgp, vgpv, vfpv regInfo) []opData {
	return []opData{
		{name: "VADD2D", argLength: 2, reg: v21, asm: "VADD", commutative: true, typ: "Vec128"},
		{name: "VADD4S", argLength: 2, reg: v21, asm: "VADD", commutative: true, typ: "Vec128"},
		{name: "VADD8H", argLength: 2, reg: v21, asm: "VADD", commutative: true, typ: "Vec128"},
		{name: "VADD16B", argLength: 2, reg: v21, asm: "VADD", commutative: true, typ: "Vec128"},
		{name: "VFADD2D", argLength: 2, reg: v21, asm: "VFADD", commutative: true, typ: "Vec128"},
		{name: "VFADD4S", argLength: 2, reg: v21, asm: "VFADD", commutative: true, typ: "Vec128"},
		{name: "VFMUL2D", argLength: 2, reg: v21, asm: "VFMUL", commutative: true, typ: "Vec128"},
		{name: "VFMUL4S", argLength: 2, reg: v21, asm: "VFMUL", commutative: true, typ: "Vec128"},
		{name: "VFSUB2D", argLength: 2, reg: v21, asm: "VFSUB", typ: "Vec128"},
		{name: "VFSUB4S", argLength: 2, reg: v21, asm: "VFSUB", typ: "Vec128"},
		{name: "VMUL4S", argLength: 2, reg: v21, asm: "VMUL", commutative: true, typ: "Vec128"},
		{name: "VMUL8H", argLength: 2, reg: v21, asm: "VMUL", commutative: true, typ: "Vec128"},
		{name: "VMUL16B", argLength: 2, reg: v21, asm: "VMUL", commutative: true, typ: "Vec128"},
		{name: "VSUB2D", argLength: 2, reg: v21, asm: "VSUB", typ: "Vec128"},
		{name: "VSUB4S", argLength: 2, reg: v21, asm: "VSUB", typ: "Vec128"},
		{name: "VSUB8H", argLength: 2, reg: v21, asm: "VSUB", typ: "Vec128"},
		{name: "VSUB16B", argLength: 2, reg: v21, asm: "VSUB", typ: "Vec128"},
		{name: "VDUPBbcast", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VDUPDbcast", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VDUPDextr", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VDUPHbcast", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VDUPSbcast", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VDUPSextr", argLength: 1, reg: v11, asm: "VDUP", aux: "UInt8", typ: "Vec128"},
		{name: "VMOVBextr", argLength: 1, reg: vgp, asm: "VMOV", aux: "UInt8", typ: "int8"},
		{name: "VMOVBins", argLength: 2, reg: vgpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
		{name: "VMOVDextr", argLength: 1, reg: vgp, asm: "VMOV", aux: "UInt8", typ: "int64"},
		{name: "VMOVDins", argLength: 2, reg: vgpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
		{name: "VMOVDins0", argLength: 2, reg: vfpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
		{name: "VMOVHextr", argLength: 1, reg: vgp, asm: "VMOV", aux: "UInt8", typ: "int16"},
		{name: "VMOVHins", argLength: 2, reg: vgpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
		{name: "VMOVSextr", argLength: 1, reg: vgp, asm: "VMOV", aux: "UInt8", typ: "int32"},
		{name: "VMOVSins", argLength: 2, reg: vgpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
		{name: "VMOVSins0", argLength: 2, reg: vfpv, asm: "VMOV", aux: "UInt8", typ: "Vec128", resultInArg0: true},
	}
}
