# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=unicode/utf16
GOFILES=\
	utf16.go\

include ../../../Make.pkg
