name: Go Telemetry Proposals
description: Changes to the telemetry upload configuration
title: "x/telemetry/config: proposal title"
labels: ["Telemetry-Proposal"]
projects: ["golang/29"]
body:
- type: textarea
  attributes:
    label: Summary
    description: >
      What change are you proposing to the upload configuration, and why?
      For new upload configuration, which new counters will be collected, what
      do they measure, and why is it important to collect them?
      Note that uploaded data must not carry sensitive user information.
      See [go.dev/doc/telemetry#proposals](https://go.dev/doc/telemetry#proposals)
      for more details on telemetry proposals.
  validations:
    required: true
- type: input
  attributes:
    label: Proposed Config Change
    description: >
      A CL containing proposed changes to the
      [config.txt](https://go.googlesource.com/telemetry/+/master/internal/chartconfig/config.txt)
      chart configuration.
      See the [chartconfig](https://pkg.go.dev/golang.org/x/telemetry/internal/chartconfig)
      package for an explanation of the chart config format.
      For an example change, see [CL 564619](https://go.dev/cl/564619).
  validations:
    required: true
