# Copyright 2010 The Go Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=net/textproto
GOFILES=\
	pipeline.go\
	reader.go\
	textproto.go\
	writer.go\

include ../../../Make.pkg
