// Code generated by 'simdgen -o godefs -goroot $GOROOT -arm64Path $ARM64_ISA_PATH go_arm64.yaml types.yaml categories.yaml'; DO NOT EDIT.

package arm64

import (
	"cmd/compile/internal/ssa"
	"cmd/compile/internal/ssagen"
	"cmd/internal/obj"
	"cmd/internal/obj/arm64"
)

func ssaGenSIMDValue(s *ssagen.State, v *ssa.Value) bool {
	var p *obj.Prog
	switch v.Op {
	case ssa.OpARM64VSHL16B,
		ssa.OpARM64VSQSHL16Bconst,
		ssa.OpARM64VUQSHL16Bconst,
		ssa.OpARM64VSSHR16B,
		ssa.OpARM64VUSHR16B:
		p = simdV11Imm(s, v, arm64.ARNG_16B)

	case ssa.OpARM64VSHL2D,
		ssa.OpARM64VSQSHL2Dconst,
		ssa.OpARM64VUQSHL2Dconst,
		ssa.OpARM64VSSHR2D,
		ssa.OpARM64VUSHR2D:
		p = simdV11Imm(s, v, arm64.ARNG_2D)

	case ssa.OpARM64VSHL4S,
		ssa.OpARM64VSQSHL4Sconst,
		ssa.OpARM64VUQSHL4Sconst,
		ssa.OpARM64VSSHR4S,
		ssa.OpARM64VUSHR4S:
		p = simdV11Imm(s, v, arm64.ARNG_4S)

	case ssa.OpARM64VSHL8H,
		ssa.OpARM64VSQSHL8Hconst,
		ssa.OpARM64VUQSHL8Hconst,
		ssa.OpARM64VSSHR8H,
		ssa.OpARM64VUSHR8H:
		p = simdV11Imm(s, v, arm64.ARNG_8H)

	case ssa.OpARM64VDUPBbcast:
		p = simdV11ImmIn1(s, v, arm64.ARNG_B)

	case ssa.OpARM64VDUPDbcast:
		p = simdV11ImmIn1(s, v, arm64.ARNG_D)

	case ssa.OpARM64VDUPHbcast:
		p = simdV11ImmIn1(s, v, arm64.ARNG_H)

	case ssa.OpARM64VDUPSbcast:
		p = simdV11ImmIn1(s, v, arm64.ARNG_S)

	case ssa.OpARM64VDUPDextr:
		p = simdV11ScalarImmIn1(s, v, arm64.ARNG_D)

	case ssa.OpARM64VDUPSextr:
		p = simdV11ScalarImmIn1(s, v, arm64.ARNG_S)

	case ssa.OpARM64VADD16B,
		ssa.OpARM64VMUL16B,
		ssa.OpARM64VSSHL16B,
		ssa.OpARM64VUSHL16B,
		ssa.OpARM64VSQSHL16B,
		ssa.OpARM64VUQSHL16B,
		ssa.OpARM64VSUB16B:
		p = simdV21(s, v, arm64.ARNG_16B)

	case ssa.OpARM64VFADD2D,
		ssa.OpARM64VADD2D,
		ssa.OpARM64VFMUL2D,
		ssa.OpARM64VSSHL2D,
		ssa.OpARM64VUSHL2D,
		ssa.OpARM64VSQSHL2D,
		ssa.OpARM64VUQSHL2D,
		ssa.OpARM64VFSUB2D,
		ssa.OpARM64VSUB2D:
		p = simdV21(s, v, arm64.ARNG_2D)

	case ssa.OpARM64VFADD4S,
		ssa.OpARM64VADD4S,
		ssa.OpARM64VFMUL4S,
		ssa.OpARM64VMUL4S,
		ssa.OpARM64VSSHL4S,
		ssa.OpARM64VUSHL4S,
		ssa.OpARM64VSQSHL4S,
		ssa.OpARM64VUQSHL4S,
		ssa.OpARM64VFSUB4S,
		ssa.OpARM64VSUB4S:
		p = simdV21(s, v, arm64.ARNG_4S)

	case ssa.OpARM64VADD8H,
		ssa.OpARM64VMUL8H,
		ssa.OpARM64VSSHL8H,
		ssa.OpARM64VUSHL8H,
		ssa.OpARM64VSQSHL8H,
		ssa.OpARM64VUQSHL8H,
		ssa.OpARM64VSUB8H:
		p = simdV21(s, v, arm64.ARNG_8H)

	case ssa.OpARM64VMOVBextr:
		p = simdVgpImmIn1(s, v, arm64.ARNG_B)

	case ssa.OpARM64VMOVDextr:
		p = simdVgpImmIn1(s, v, arm64.ARNG_D)

	case ssa.OpARM64VMOVHextr:
		p = simdVgpImmIn1(s, v, arm64.ARNG_H)

	case ssa.OpARM64VMOVSextr:
		p = simdVgpImmIn1(s, v, arm64.ARNG_S)

	case ssa.OpARM64VMOVBins:
		p = simdVgpvResultInArg0ImmOutIn0(s, v, arm64.ARNG_B)

	case ssa.OpARM64VMOVDins:
		p = simdVgpvResultInArg0ImmOutIn0(s, v, arm64.ARNG_D)

	case ssa.OpARM64VMOVHins:
		p = simdVgpvResultInArg0ImmOutIn0(s, v, arm64.ARNG_H)

	case ssa.OpARM64VMOVSins:
		p = simdVgpvResultInArg0ImmOutIn0(s, v, arm64.ARNG_S)

	case ssa.OpARM64VMOVDins0:
		p = simdVfpvResultInArg0ImmOutIn1(s, v, arm64.ARNG_D)

	case ssa.OpARM64VMOVSins0:
		p = simdVfpvResultInArg0ImmOutIn1(s, v, arm64.ARNG_S)

	default:
		// Unknown reg shape
		return false
	}

	// Ensure p is marked as used (may not be used in all generated code paths)
	_ = p
	return true
}
