#!/bin/sh

x() {
	echo '--- ' "$@"
	"$@"
	echo '---'
	echo
}

x go help
x go help build
x go help clean
x go help install
x go help fix
x go help fmt
x go help get
x go help list
x go help test
x go help version
x go help vet
x go help gopath
x go help importpath
x go help remote
