# Copyright 2011 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=html/template
GOFILES=\
	attr.go\
	clone.go\
	content.go\
	context.go\
	css.go\
	doc.go\
	error.go\
	escape.go\
	html.go\
	js.go\
	template.go\
	transition.go\
	url.go\

include ../../../Make.pkg
