# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=cmath

GOFILES=\
	abs.go\
	asin.go\
	conj.go\
	exp.go\
	isinf.go\
	isnan.go\
	log.go\
	phase.go\
	polar.go\
	pow.go\
	rect.go\
	sin.go\
	sqrt.go\
	tan.go\

include ../../../Make.pkg
