# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=crypto/cipher
GOFILES=\
	cbc.go\
	cipher.go\
	ctr.go\
	io.go

include ../../../Make.pkg
