# Copyright 2011 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../../Make.inc

TARG=exp/template/html
GOFILES=\
	context.go\
	css.go\
	escape.go\
	html.go\
	js.go\
	url.go\

include ../../../../Make.pkg
