# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=big
GOFILES=\
	arith.go\
	arith_decl.go\
	int.go\
	nat.go\
	rat.go\

OFILES=\
	arith_$(GOARCH).$O\

include ../../../Make.pkg
