# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../Make.$(GOARCH)

TARG=cgo
GOFILES=\
	ast.go\
	gcc.go\
	main.go\
	out.go\
	util.go\

include ../../Make.cmd
