# Copyright 2011 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=exp/regexp
GOFILES=\
	exec.go\
	regexp.go\

include ../../../Make.pkg
