# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Help for debugging.
dump:	dump.go
	go clean -i  # remove installed copy
	go build -t gob-debug -o dump dump.go

