# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.inc

TARG=crypto/x509
GOFILES=\
	cert_pool.go\
	pkcs1.go\
	pkcs8.go\
	verify.go\
	x509.go\

include ../../../Make.pkg
