# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ../../../Make.$(GOARCH)

TARG=crypto/rsa
GOFILES=\
	rsa.go\
	pkcs1v15.go\

include ../../../Make.pkg
