#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
[ -z "$gofiles" ] && exit 0

tempdir=$(mktemp -d "${TMPDIR}go_precommit.XXXXX")
tempfiles=""

for file in $gofiles; do
    tempname="$tempdir/$file"
    relative_dir=$(dirname "$file")

    mkdir -p "$tempdir/$relative_dir"
    git show ":$file" > "$tempname"

    tempfiles="$tempfiles $tempname"
done

output=$(gofmt -l $tempfiles)
output=$(echo "$output" | sed "s|$tempdir|$PWD|g")

rm -rf $tempdir

[ -z "$output" ] && exit 0

# Some files are not gofmt'd. Print message and fail.

echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $output; do
	echo >&2 "  gofmt -w $fn"
done

exit 1
