#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
[ -z "$gofiles" ] && exit 0

tempdir=$(mktemp -d "${TMPDIR}go_precommit.XXXXX")
unformatted=""

for file in $gofiles; do
    tempname="$tempdir/$file"
    relative_dir=$(dirname "$file")

    mkdir -p "$tempdir/$relative_dir"
    git show ":$file" > "$tempname"

    output=$(gofmt -l "$tempname")

    [ -n "$output" ] && unformatted="$unformatted $file"
done

[ -z "$unformatted" ] && exit 0

rm -rf $tempdir

# Some files are not gofmt'd. Print message and fail.

echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
	echo >&2 "  gofmt -w $PWD/$fn"
done

exit 1
