name: go vet
on:
  pull_request:
  workflow_dispatch:

jobs:
  go-vet:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build toolchain and test (host amd64)
        run: |
            # install bootstrap Go
            set -euxo pipefail
            BOOT=/tmp/go-bootstrap
            curl -fsSL https://go.dev/dl/go1.25.0.linux-amd64.tar.gz -o /tmp/go.tar.gz
            tar -C /tmp -xzf /tmp/go.tar.gz
            mv /tmp/go "$BOOT"
            export GOROOT_BOOTSTRAP="$BOOT"
            
            # build toolchain
            cd "$GITHUB_WORKSPACE/src"
            ./make.bash
            # run go vet only on packages with changed Go files under src/ relative to PR base
            export GOROOT="$GITHUB_WORKSPACE"
            cd "$GITHUB_WORKSPACE"
            # Determine base commit for PR; fallback to origin/${GITHUB_BASE_REF:-main}
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            if [ -z "${BASE_SHA}" ]; then
              git fetch --no-tags origin "+refs/heads/*:refs/remotes/origin/*"
              BASE_REF="${GITHUB_BASE_REF:-main}"
              BASE_SHA="origin/${BASE_REF}"
            fi
            # Collect changed .go files under src/
            mapfile -t CHANGED < <(git diff --name-only --diff-filter=ACMRT "${BASE_SHA}" HEAD -- '*.go' | grep -E '^src/' || true)
            if [ ${#CHANGED[@]} -eq 0 ]; then
              echo "No changed Go files under src/; skipping vet."
              exit 0
            fi
            # Derive unique package directories relative to src/
            mapfile -t PKG_DIRS < <(printf '%s\n' "${CHANGED[@]}" | sed 's|^src/||' | xargs -r -n1 dirname | sort -u)
            cd "$GOROOT/src"
            ok_dirs=()
            for d in "${PKG_DIRS[@]}"; do
              # Filter to valid packages (go list must succeed)
              if GO111MODULE=off "$GOROOT/bin/go" list "./$d" >/dev/null 2>&1; then
                ok_dirs+=("./$d")
              fi
            done
            if [ ${#ok_dirs[@]} -eq 0 ]; then
              echo "No valid Go packages to vet; exiting."
              exit 0
            fi
            echo "Vetting packages:"
            printf '%s\n' "${ok_dirs[@]}"

            # Run go vet and capture output without failing immediately
            # Disable xtrace to reduce noise in logs while filtering
            set +x
            set +e
            GO111MODULE=off "$GOROOT/bin/go" vet -v "${ok_dirs[@]}" > /tmp/vet.out 2>&1
            VET_STATUS=${PIPESTATUS[0]}
            set -e
            # Re-enable xtrace if desired (leave disabled to keep logs clean)

            if [ "$VET_STATUS" -eq 0 ]; then
              echo "go vet passed with no errors."
              exit 0
            fi

            # Build a set of changed files relative to $GOROOT/src
            mapfile -t CHANGED_REL < <(printf '%s\n' "${CHANGED[@]}" | sed 's|^src/||')
            declare -A CHANGED_SET=()
            for f in "${CHANGED_REL[@]}"; do
              CHANGED_SET["$f"]=1
              CHANGED_SET["./$f"]=1
            done

            # Filter vet output: keep errors only for files modified in this PR
            KEPT_ERRORS=0
            IGNORED_ERRORS=0
            > /tmp/vet.kept
            > /tmp/vet.ignored

            while IFS= read -r line; do
              if [[ "$line" =~ ^([[:alnum:]_./-]+\.go):([0-9]+): ]]; then
                file="${BASH_REMATCH[1]}"
                if [[ ${CHANGED_SET[$file]+_} ]]; then
                  echo "$line" >> /tmp/vet.kept
                  KEPT_ERRORS=$((KEPT_ERRORS+1))
                else
                  echo "$line" >> /tmp/vet.ignored
                  IGNORED_ERRORS=$((IGNORED_ERRORS+1))
                fi
              fi
            done < /tmp/vet.out

            if [ "$KEPT_ERRORS" -gt 0 ]; then
              echo "go vet errors in modified files ($KEPT_ERRORS):" >&2
              cat /tmp/vet.kept >&2
              if [ "$IGNORED_ERRORS" -gt 0 ]; then
                echo "go vet diagnostics ignored in unmodified files ($IGNORED_ERRORS):" >&2
                cat /tmp/vet.ignored >&2
              fi
              exit 1
            else
              echo "go vet reported issues only in unmodified files ($IGNORED_ERRORS); ignoring." >&2
              # Optionally show ignored diagnostics; comment out next line to hide details
              cat /tmp/vet.ignored >&2 || true
              exit 0
            fi